# coding: utf-8

"""
    hcOS Developer Experience

    hcOS Developer Experience API  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from hcos_client.models.person_role import PersonRole  # noqa: F401,E501


class Person(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'role': 'PersonRole',
        'root': 'str',
        'extension': 'str',
        'last_name': 'str',
        'first_name': 'str',
        'middle_name': 'str'
    }

    attribute_map = {
        'role': 'role',
        'root': 'root',
        'extension': 'extension',
        'last_name': 'last_name',
        'first_name': 'first_name',
        'middle_name': 'middle_name'
    }

    def __init__(self, role=None, root=None, extension=None, last_name=None, first_name=None, middle_name=None):  # noqa: E501
        """Person - a model defined in Swagger"""  # noqa: E501
        self._role = None
        self._root = None
        self._extension = None
        self._last_name = None
        self._first_name = None
        self._middle_name = None
        self.discriminator = None
        self.role = role
        self.root = root
        self.extension = extension
        if last_name is not None:
            self.last_name = last_name
        if first_name is not None:
            self.first_name = first_name
        if middle_name is not None:
            self.middle_name = middle_name

    @property
    def role(self):
        """Gets the role of this Person.  # noqa: E501


        :return: The role of this Person.  # noqa: E501
        :rtype: PersonRole
        """
        return self._role

    @role.setter
    def role(self, role):
        """Sets the role of this Person.


        :param role: The role of this Person.  # noqa: E501
        :type: PersonRole
        """
        if role is None:
            raise ValueError("Invalid value for `role`, must not be `None`")  # noqa: E501

        self._role = role

    @property
    def root(self):
        """Gets the root of this Person.  # noqa: E501


        :return: The root of this Person.  # noqa: E501
        :rtype: str
        """
        return self._root

    @root.setter
    def root(self, root):
        """Sets the root of this Person.


        :param root: The root of this Person.  # noqa: E501
        :type: str
        """
        if root is None:
            raise ValueError("Invalid value for `root`, must not be `None`")  # noqa: E501

        self._root = root

    @property
    def extension(self):
        """Gets the extension of this Person.  # noqa: E501


        :return: The extension of this Person.  # noqa: E501
        :rtype: str
        """
        return self._extension

    @extension.setter
    def extension(self, extension):
        """Sets the extension of this Person.


        :param extension: The extension of this Person.  # noqa: E501
        :type: str
        """
        if extension is None:
            raise ValueError("Invalid value for `extension`, must not be `None`")  # noqa: E501

        self._extension = extension

    @property
    def last_name(self):
        """Gets the last_name of this Person.  # noqa: E501


        :return: The last_name of this Person.  # noqa: E501
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name):
        """Sets the last_name of this Person.


        :param last_name: The last_name of this Person.  # noqa: E501
        :type: str
        """

        self._last_name = last_name

    @property
    def first_name(self):
        """Gets the first_name of this Person.  # noqa: E501


        :return: The first_name of this Person.  # noqa: E501
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """Sets the first_name of this Person.


        :param first_name: The first_name of this Person.  # noqa: E501
        :type: str
        """

        self._first_name = first_name

    @property
    def middle_name(self):
        """Gets the middle_name of this Person.  # noqa: E501


        :return: The middle_name of this Person.  # noqa: E501
        :rtype: str
        """
        return self._middle_name

    @middle_name.setter
    def middle_name(self, middle_name):
        """Sets the middle_name of this Person.


        :param middle_name: The middle_name of this Person.  # noqa: E501
        :type: str
        """

        self._middle_name = middle_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Person, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Person):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
